### ISSUE TITLE
data

### ISSUE THREAD

**Issue by catherine-qian** [jasongief/PSP_CVPR_2021#1]
Dear authors,

Thanks for opening this work!
I have downloaded the data as:
data/AVE_Dataset
data/audio_feature.h5 prob_label.h5 right_labels.h5 visual_feature.h5

Looks like it miss the other files e.g. audio_feature_noisy.h5 visual_feature_noisy.h5

Besides, could you please let me know the environment you use?

**Comment by jasongief** [comment]
Hi, thanks for your interest. The missing noisy feature files can be downloaded in the following links: visual_feature_noisy.h5: https://drive.google.com/file/d/1I3OtOHJ8G1-v5G2dHIGCfevHQPn-QyLh/view,
I remember other files can be found in the https://github.com/YapengTian/AVE-ECCV18.
Anyway, I have updated the README.md and all the other files you need are available at: https://drive.google.com/drive/folders/1q8GYBqfkyDDAnVMClrMTXR9YzH9UPcSM


As for the environment, I have updated the requirements.txt just now.

**Comment by catherine-qian** [comment]
dear authors,

thanks for your help!
