### ISSUE TITLE
如何在特征提取时获得4143组数据特征而不是4097组

### ISSUE THREAD

**Issue by tancoco** [jasongief/PSP_CVPR_2021#11]

**Comment by jasongief** [comment]
嗨，你好啊，抱歉回复晚了。没记错的话，AVE dataset好像确实就4097个video，因为有一些video是可以被分为多个类别的。如果想自己提取特征的话，需要去video list里找一下上述重复的video，然后处理下索引就好了把。

**Comment by jasongief** [comment]
嗨，你好啊，抱歉回复晚了。没记错的话，AVE dataset好像确实就4097个video，因为有一些video是可以被分为多个类别的。如果想自己提取特征的话，需要去video list里找一下上述重复的video，然后处理下索引就好了吧。
