### ISSUE TITLE
training time and environment

### ISSUE THREAD

**Issue by catherine-qian** [jasongief/PSP_CVPR_2021#2]
Dear authors,

Could you please kindly let me know how many GPUs you used for training the model? and how long will it take? Do you set the early stop or specify the overall training epochs?

Thanks a lot for your help!

**Comment by jasongief** [comment]
Hi, all the experiments are conducted on one NVIDIA 1080Ti GPU. The training epoch is empirically set to 300. In fact, according to the best performance, the training epoch is around 200 for the fully supervised setting and around 30 for the weakly supervised setting. 
The total training process is normally not more than 1 hour. 
It seems that we do not set the early stopping, you can refine the codes accordingly. Also if you want to train from scratch, you may make some adjustments as introduced in README.

**Comment by catherine-qian** [comment]
Thanks for your answer!
