### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by jiangerxiaozhao** [jasongief/PSP_CVPR_2021#4]
Good work! When I train from scratch for the fully supervised setting,  the AVE localization accuracy can achieve 75.8% or 75.2% with different seeds.  Any suggestions?

**Comment by jasongief** [comment]
Hi, thanks for your interest. In my experiments, I just fix the seed to this value and do not take care of it. According to your report, I guess the random value has some effects on the data sampling and may also affects the PSP model initialization. You may try to refine the codes of data processing or the initialization method of the model.

**Comment by jiangerxiaozhao** [comment]
What is type of GPU do you use?

**Comment by jasongief** [comment]
GeForce GTX 1080 Ti
