### ISSUE TITLE
The question of result

### ISSUE THREAD

**Issue by zwy1996** [jasongief/PSP_CVPR_2021#5]
Hi, nice work!

I was very sorry to bother you. When I used your code, there were two results(val and test), I had read  your paper, but I did not see the description of result. So, which result did you use in your paper?  val or test dataset?

Thank you very  much!

**Comment by jasongief** [comment]
Hi, thanks for your interest.  The results reported in our paper are conducted on the test set.

**Comment by zwy1996** [comment]
OK, I get it.

Thanks for your response in time!!

Thank you very much!
