### ISSUE TITLE
Why do some Linear layers have bias set to False?

### ISSUE THREAD

**Issue by varshanth** [jasongief/PSP_CVPR_2021#6]
Hi,

Thanks for your code and congrats on the paper accept. I was going through your code and your model definition. I have 2 enquiries:

1) Why do some Linear layers have bias set to False?
2) You init linear layers with Xavier Uniform initialization. Does initialization with other methods influence your result?

Thanks!

**Comment by jasongief** [comment]
Hi, thanks for your attention to these details.
1. The linear layers defined in the PSP aim to perform a linear transformation to the audio or visual feature, we just opt to implement it by a matrix multiplication without adding bias, you may try to set the bias to True and I guess the result is competitive to (or may be lower than) current setup.
2. I am afraid that different initialization methods would have some influence on the model training. Obviously, a good initialization method would help to achieve the optimal situation.
