### ISSUE TITLE
what information is prob_label.h5 generated based on

### ISSUE THREAD

**Issue by chocokassy** [jasongief/PSP_CVPR_2021#7]
Hello, I would like to ask what information is prob_label generated based on? At first I thought it corresponds to the information in annotation.txt, because they all have 4143 lines, but I found that actually prob_label does not correspond to annotation, because the maximum probability of displaying the second line in prob_label is the background.
.

**Comment by jasongief** [comment]
Sorry for the late reply.  The prob_label file is the label used in the weakly supervised setting, it tells the proportion of the background and event segments. You can refer to Sec.3 for details.

**Comment by chocokassy** [comment]
thanks a lot!! Thank you very much for your contribution.
