### ISSUE TITLE
How to generate attention map?

### ISSUE THREAD

**Issue by chocokassy** [jasongief/PSP_CVPR_2021#8]
Can you provide the code to generate the attention map? I tried to run "attention_visualization" of AVE-ECCV18, and use “PSP_fully.pt” to replace the model of the original code, but an error "Nonetype object has no attribute register_forward_hook" appeared, I know it was caused by the replacement of the model, but I don’t know how to solve.

**Comment by jasongief** [comment]
I am not quite clear about your question. The "PSP_fully.pt" can be directly loaded in this project to generate attention maps just like figure. 4 in our paper. I am afraid that you can not load this pretrained PSP model in the AVE-ECCV18 project.

As for how to generate the attention map, the "attention_visualization" in AVE-ECCV18 can do this with the API provided by opencv.

**Comment by LllHan** [comment]
Have you solved this problem? I had the same problem. How did you solve it?
