### ISSUE TITLE
Why the right_labels.h5 does not contain all the video labels?

### ISSUE THREAD

**Issue by chocokassy** [jasongief/PSP_CVPR_2021#9]
Hello, I would like to ask why only the first category of video classification (Church bell) labels per second are given in right_labels.h5, only the first 188 rows show whether there is an event per second, and the values of all subsequent rows It is all 0. Logically, it should contain all the labels of all videos for 10 seconds. If an event occurs, it will be 1, otherwise is background, is 0.
I am very sorry to bother you all the time, and I am very grateful for your contribution.
![1](https://user-images.githubusercontent.com/32349968/147667847-7c7c1f38-a0af-4f97-baed-8a9ee36fcbb8.png)

**Comment by jasongief** [comment]
The shape of the matrix in right_label.h5 should be (4143, 10, 29), where each [10, 29] is the label for one video (10 segments), each vector with size [1, 29] tells the event category label (totally 29 categories for AVE dataset).

I have checked that file, it should be correct. Every vector (row) should set an element to 1 representing its category.
